# Imagen base
FROM docker.io/bitnami/laravel:10

# Copiamos los archivos de nuestra aplicación
COPY . /app

# Establecemos el directorio de trabajo
WORKDIR /app

# Exponemos el puerto 8000
EXPOSE 8000
